Chart refactor
distribworks/dkron-helm pull request #3
Opened 2021-06-14 16:01 UTC by FedeBev

Since there's still an [open issue](https://github.com/distribworks/dkron/issues/676) in the main repo and I've the feeling this chart has been dropped, I've decided to rework it completely.

The main differences are:
- different values for server and agent
- HPA
- it works (seriously, the original didn't work for me because of [this issue](https://github.com/distribworks/dkron/issues/676#issuecomment-586953312))
- server is deployed using a StatefulSet, allowing the usage of PV (through volume claim template), resolving #2
- a custom image can be specified, useful when an image with a custom plugin should be used
- I've no longer seen #1, maybe just because of dkron upgrade (3.1.6)

Known issues:
- no health check specified, always [because of this](https://github.com/distribworks/dkron/issues/676#issuecomment-586953312) (help wanted)

Let me know what are yout thoughts, I'm open to feedback available to make any changes

2021-11-07 22:37 UTC, victorcoder commented
Sorry for the mega-delay here @FedeBev, thank you very much for the work! I had not prioritized the K8s work until now, going to test this and merge if it works.

2021-11-08 18:16 UTC, victorcoder requested changes
Aside from the nitpicks, it LGTM but I have been unable to do a rolling restart without breaking the cluster, what's your strategy?

2021-11-08 18:16 UTC, victorcoder commented on dkron/templates/envsConfigmap.yaml
> +  {{- end }}
Line feed

2021-11-08 18:16 UTC, victorcoder commented on dkron/templates/serviceaccount.yaml
> +{{- end }}
LF

2021-11-09 10:08 UTC, FedeBev commented
What kind of problem are you facing @victorcoder? I just tried a rolling update from version v3.1.8 to v3.1.10 and everything went good except for a slight leader election delay.

Do you mind sharing your values and some details about your cluster?

I've just fixed the missing newlines and cleaned up the sample values file

2021-11-14 22:27 UTC, victorcoder commented
I just do a `helm install` `helm upgrade` and the rolling is too fast for the leader election to happen correctly, when done rolling there's no leader in the cluster, all nodes ends up as followers.

Are you tweeking some other options?

2021-11-24 09:32 UTC, FedeBev commented
No additional tweek on my configuration.

This also happens to me, but after a few seconds after the end of the rollout a new leader is elected again and everything goes fine.

We can try to tune the rollout strategy, but taking into account the [issue about the kubernetes discovery](https://github.com/distribworks/dkron/issues/676#issuecomment-586953312), I don't think we can achieve something better with helm. An operator would solve the issue, but it's a huge effort.

2021-11-25 09:03 UTC, vcastellm commented
@FedeBev what about a liveness, readiness check?

2021-11-25 09:11 UTC, FedeBev commented
@vcastellm in the  [issue about the kubernetes discovery](https://github.com/distribworks/dkron/issues/676#issuecomment-586953312) I've mentioned before, you can find why I wasn't able to use those.

I don't see any other possible way right now. I guess we should change something about how dkron starts or request a PR to the kubernetes discovery library.
In my opinion, the point is that dkron should be able to discover itself when the pod is running (/health returns 200), NOT when is ready. This way the k8s discovery works and we can implement a useful /health and ready probe.

2021-11-25 09:14 UTC, vcastellm commented
Understood, thanks, I will take a look on how we can improve the /health endpoint

2021-11-25 11:19 UTC, FedeBev commented
Keep me posted, I'd be glad to help.
Dkron could become a core component for a project I'm working on  however our platform relies entirely on K8s and this is a big issue

2021-12-05 13:40 UTC, Espina2 commented
I'm also very interested in this fix. @vcastellm @FedeBev anything that I can do to make this happen? Also, is this not better than the currently available chart?

2021-12-07 09:28 UTC, FedeBev commented
@Espina2 the chart is working on my cluster in a dev environment, but it's still very young and there's still a long way to go before being production ready.
There's an issue with the k8s discovery that makes you dkron cluster unavailable due to master election during the rolling upgrade.

2023-03-01 16:52 UTC, omarzouk commented
hello! also highly interested in this. Has anyone come up with a way to work around the discovery issue? any thoughts on how to proceed?

2023-03-05 22:41 UTC, merged

2023-03-05 22:42 UTC, vcastellm commented
Merged this PR and added some changes, I'll take over from here.